### ISSUE TITLE
StackOverflowError during template instantiation when same name is chosen

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#421]
Consider following schemas:
`templates.zs`
```
package templates;
struct MyTemplate<T>
{
    T field;
};
```

`test.zs`
```
package test;

import templates.*;

instantiate MyTemplate<uint32> MyTemplate;
```
Zserio compilation ends with the following error:
```
Parsing test.zs
Parsing templates.zs
[ERROR] Internal error: java.lang.StackOverflowError
	at zserio.ast.TypeReference.visitChildren(TypeReference.java:61)
	at zserio.ast.ZserioAstTypeResolver.visitTypeReference(ZserioAstTypeResolver.java:62)
        ...
```

Note that when the single import is used in `test.zs`, proper error is fired:
```
-import templates.*;
+import templates.MyTemplate;
```
```
Parsing test.zs
Parsing templates.zs
[ERROR] templates.zs:2:8:     Found here
[ERROR] test.zs:5:32:     Found here
[ERROR] test.zs:5:13: Ambiguous symbol 'MyTemplate'

```

**Comment by Mi-La** [comment]
Check also subtypes with the same use-case.
