### ISSUE TITLE
JsonMappingException is thrown when trying to serialize an Array to Json using Jackson ObjectMapper

### ISSUE THREAD

**Issue by karthikarjunagi-tomtom** [ndsev/zserio#527]
The `Array` created using the constructor `public Array(RawArray rawArray, ArrayTraits arrayTraits, ArrayType arrayType)` creates an infinite recursive `ArrayTraits` and `PackedArrayTraits`.

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: zserio.runtime.array.ArrayTraits$VarUInt16ArrayTraits["packedArrayTraits"]->zserio.runtime.array.PackedArrayTraits$IntegralPackedArrayTraits["arrayTraits"]->zserio.runtime.array.ArrayTraits$VarUInt16ArrayTraits["packedArrayTraits"]->zserio.runtime.array.PackedArrayTraits$IntegralPackedArrayTraits["arrayTraits"]->....->zserio.runtime.array.PackedArrayTraits$IntegralPackedArrayTraits["arrayTraits"])
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:789)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
```

**Example code:**

```
import java.io.IOException;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import com.fasterxml.jackson.databind.ObjectMapper;

import zserio.runtime.array.ArrayType;

public class JsonTest {

    public static void main(String[] args) throws IOException {

        final short[] shortArray = {1, 2, 3, 4, 5, 6};
        final zserio.runtime.array.Array shortRawArray = new zserio.runtime.array.Array(
                new zserio.runtime.array.RawArray.ShortRawArray(shortArray),
                new zserio.runtime.array.ArrayTraits.VarUInt16ArrayTraits(),
                ArrayType.NORMAL);

        final ObjectMapper objectMapper = new ObjectMapper().setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.NONE)
                .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY).enable(SerializationFeature.INDENT_OUTPUT)
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        System.out.println(objectMapper.writeValueAsString(shortRawArray));
    }
}
```

**Comment by mikir** [comment]
Thanks for the information but it seems like the Jackson problem. Jackson does not like the bidirectional relationships which are used in Zserio Java Arrays.

If you need to make JSON export, we recommend to use `zserio.runtime.DebugStringUtil.toJsonFile()` method implemented directly in [zserio runtime](https://zserio.org/doc/runtime/latest/java/).

**Comment by karthikarjunagi-tomtom** [comment]
That works :) Thanks for the quick response and the tip.
